### ISSUE TITLE
m3u8 not play 

### ISSUE THREAD

**Issue by emyl1** [Gratenes/m3u8CloudflareWorkerProxy#7]
I have install m3u proxy but its not working

**Comment by rahuloberai** [comment]
> I have install m3u proxy but its not working 

You need to send origin parameter too.

**Comment by tzanta10** [comment]
how to do this can you help me pleas i will pay you !

**Comment by emyl1** [comment]
> > I have install m3u proxy but its not working
> 
> You need to send origin parameter too.
can we talk on discord?  I need your help!

**Comment by rahuloberai** [comment]
> > > I have install m3u proxy but its not working
> > 
> > 
> > You need to send origin parameter too.
> > can we talk on discord?  I need your help!

okay, 
userid: rahuloberai
