### ISSUE TITLE
How to deploy outside of cloudflare

### ISSUE THREAD

**Issue by sussy-code** [Gratenes/m3u8CloudflareWorkerProxy#9]
I would like to host this on my VPS using coolify instead of cloudflare do you know how I could do this? Thanks!

**Comment by Gratenes** [comment]
I do not have any intention of supporting a runtime which is not cloudflare workers with this project, but https://github.com/vynxc/M3U8Proxy might be what your looking for.

**Comment by Tommy0412** [comment]
> I would like to host this on my VPS using coolify instead of cloudflare do you know how I could do this? Thanks!

Use this mod https://github.com/FOSWLY/m3u8-proxy-worker/tree/main/deno
its same script modified for deno. Deno is alternative for nodejs
